name: "Check Branch"

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        if: github.base_ref == 'master' && github.head_ref != 'staging'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            We regret to inform you that you are currently not able to merge your changes into the master branch due to restrictions applied by our SRE team. To proceed with merging your changes, we kindly request that you create a pull request from the staging branch. Our team will then review the changes and work with you to ensure a successful merge into the master branch.
      - name: Check branch
        if: github.base_ref == 'master' && github.head_ref != 'staging'
        run: |
          echo "ERROR: We regret to inform you that you are currently not able to merge your changes into the master branch due to restrictions applied by our SRE team. To proceed with merging your changes, we kindly request that you create a pull request from the staging branch. Our team will then review the changes and work with you to ensure a successful merge into the master branch."
          exit 1
